version: '4'

services:
  telegram_bot:
    container_name: bot
    image: telegram_bot
    build: ./telegram_bot
    env_file:
      - ./telegram_bot/.env
    restart: unless-stopped

  api:
    container_name: api
    image: bot_api
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8008
    env_file:
      - ./api/.env
    ports:
      - '8008:8008'
    restart: unless-stopped

